### ISSUE TITLE
Add InsightIDR Backend

### ISSUE THREAD

**Issue by mbabinski** [magicsword-io/sigconverter.io#1]
Hello! Love the project, I will definitely be a user and promoter. 😄 

I suggest adding the Rapid7 InsightIDR backend to the project: https://github.com/SigmaHQ/pySigma-backend-insightidr

It is compatible with the latest version of pySigma (it will work fine with pySigma 9.x as well).

**Comment by nasbench** [comment]
Due to some incompatibility between backends, the change to add InsightIDR has been reverted for now. We'll work on a way to add it soon :)
