### ISSUE TITLE
API Documentation?

### ISSUE THREAD

**Issue by coreyogburn** [magicsword-io/sigconverter.io#17]
I just ran into an issue where I unknowingly passed in bad yaml but got a 200 response back with an error message in the body. Is there documentation around this behavior? Is it enough to check if the response starts with `Error:` to determine if the request was actually successful or not?

**Comment by nasbench** [comment]
Hi @coreyogburn 

There isn't documentation around this. But yes, its enough to check for the keyword ``Error:`` to find conversion type errors (even if the code is 200). You can see the implementation here https://github.com/magicsword-io/sigconverter.io/blob/main/run.py#L63-L64

We will enhance the error handling to return appropriate error codes soon. For example `400` when a bad yaml is provided, etc.

Thanks for raising this issue.

**Comment by M3NIX** [comment]
fixed with #19
