### ISSUE TITLE
ecs_windows pipeline on sigconverter.io

### ISSUE THREAD

**Issue by kt9ck** [magicsword-io/sigconverter.io#18]
Would like the ecs_windows pipeline from the pysigma project on sigconverter.io to use with ELK for logs from winlogbeats.

**Comment by nasbench** [comment]
Thanks for opening this issue @kt9ck. It looks like the elasticsearch backend was omitting elasticsearch as an allowed backend from the defined pipelines.
A fix is underway and once its merged and available upstream, it'll be available in sigconverter as well after upgrade.

**Comment by nasbench** [comment]
Resolved by new Elastic backend release https://github.com/SigmaHQ/pySigma-backend-elasticsearch/releases/tag/v1.0.10
