### ISSUE TITLE
Bump pySigma version?

### ISSUE THREAD

**Issue by svnscha** [magicsword-io/sigconverter.io#29]
Hi all,
first of all - great project!

I would like to open a PR to add our converter [pySigma-backend-uberAgent](https://github.com/vastlimits/pySigma-backend-uberAgent) to sigconverter.io.

However, as we have just implemented that backend we have started using a current version of pySigma and I can't add our backend as dependency.

Will you guys update pySigma to a newer version or will that requirement for `pysigma = "0.9.11"` stay a while? If yes, I would check if I can backport our backend to the old version.

**Comment by nasbench** [comment]
Hey @svnscha thanks for opening this.

We're currently in the process of studying the ability to offer 2 pySigma versions (at least) the latest version and a previous one for the exact reason you mentioned. The current setup of pysigma requires you to specify version and if the people maintaining it do not upgrade it, it'll fail.

So for now it'll stay like this but we want to upgrade it as soon as we can and support as many backend as possible. Also specifically to be able to offer the templating feature from the web.

I'll keep you posted :)

**Comment by svnscha** [comment]
Hey @nasbench - super quick response. Thanks! I have some additional information that might be helpful. I have locally tested to update all the packages.

My updated version looks like this:

```
[tool.poetry.dependencies]
python = "^3.10"
flask = "3.0.0"
pysigma = "^0.10.9"
sigma-cli = "^0.7.10"
pysigma-backend-loki = "^0.10.3"
pysigma-backend-carbonblack = "^0.1.5"
pysigma-backend-cortexxdr = "^0.1.2"
pysigma-backend-elasticsearch = "^1.0.9"
pysigma-backend-opensearch = "^1.0.1"
pysigma-backend-qradar-aql = "^0.2.5"
pysigma-backend-sentinelone = "^0.1.3"
pysigma-backend-splunk = "^1.0.3"
pysigma-backend-insightidr = "^0.2.2"
pysigma-pipeline-crowdstrike = "^1.0.1"
pysigma-pipeline-sysmon = "^1.0.3"
pysigma-pipeline-windows = "^1.1.1"
pysigma-backend-uberagent = "^0.3.61"
```

As you see most backends support a newer version. 

Unfortunately, a couple of backends don't.

```
pysigma-backend-azure = {git = "https://github.com/sifex/pySigma-backend-azure.git", rev = "9c35b78cd4d4891e1b46ccf21ed555ffb10b96e6"}
pysigma-backend-microsoft365defender = {git = "https://github.com/AttackIQ/pySigma-backend-microsoft365defender.git", rev = "731db4b6c7cbab8898973b4350d93268e135c495"}
pysigma-backend-stix = {git = "https://github.com/barvhaim/pySigma-backend-stix", rev = "0d7c05e187249c26f5abb99f63bf839c78705d1e"}
pysigma-backend-qradar = "0.3.3"
pysigma-backend-sentinelone-pq = "0.1.1"
```

Instead of downgrading our backend I would rather contribute helping to support multiple pySigma versions. Is there something I can help with?

**Comment by nasbench** [comment]
Hey thanks for the test, i didn't notice that most of them are compatible with the latest version. From my pov i'm fine with loosing these 5 for now. I'll ask the rest of the team for their opinion.

As far as additional help. I don't know if the incompatible backends only require a version update in the pysigma plugin or something will break. 

From our side we're trying to host 2 versions of pysigma under 2 different subdomains to make it easier as this will always be a problem to get everyone to an acceptable state.

I'm checking with the team on this task to see if there's an update from their side :)

**Comment by nasbench** [comment]
This is now resolved. You can check out https://beta.sigconverter.io/ for the version of the website using the latest pySigma version. 

Here is an example of the UberAgent [conversion](https://beta.sigconverter.io/#backend=uberagent&format=default&pipeline=&rule=dGl0bGU6IFN1c3BpY2lvdXMgU1lTVEVNIFVzZXIgUHJvY2VzcyBDcmVhdGlvbgppZDogMjYxN2U3ZWQtYWRiNy00MGJhLWIwZjMtOGY5OTQ1ZmU2YzA5CnN0YXR1czogdGVzdApkZXNjcmlwdGlvbjogRGV0ZWN0cyBhIHN1c3BpY2lvdXMgcHJvY2VzcyBjcmVhdGlvbiBhcyBTWVNURU0gdXNlciAoc3VzcGljaW91cyBwcm9ncmFtIG9yIGNvbW1hbmQgbGluZSBwYXJhbWV0ZXIpCnJlZmVyZW5jZXM6CiAgICAtIEludGVybmFsIFJlc2VhcmNoCiAgICAtIGh0dHBzOi8vdG9vbHMudGhlaGFja2VyLnJlY2lwZXMvbWltaWthdHovbW9kdWxlcwphdXRob3I6IEZsb3JpYW4gUm90aCAocnVsZSksIERhdmlkIEFORFJFIChhZGRpdGlvbmFsIGtleXdvcmRzKQpkYXRlOiAyMDIxLzEyLzIwCm1vZGlmaWVkOiAyMDIyLzA0LzI3CmxvZ3NvdXJjZToKICAgIGNhdGVnb3J5OiBwcm9jZXNzX2NyZWF0aW9uCiAgICBwcm9kdWN0OiB3aW5kb3dzCmRldGVjdGlvbjoKICAgIHNlbGVjdGlvbjoKICAgICAgICBJbnRlZ3JpdHlMZXZlbDogU3lzdGVtCiAgICAgICAgVXNlcnxjb250YWluczogIyBjb3ZlcnMgbWFueSBsYW5ndWFnZSBzZXR0aW5ncwogICAgICAgICAgICAtICdBVVRIT1JJJwogICAgICAgICAgICAtICdBVVRPUkknCiAgICBzZWxlY3Rpb25fc3BlY2lhbDoKICAgICAgICAtIEltYWdlfGVuZHN3aXRoOgogICAgICAgICAgICAtICdcY2FsYy5leGUnCiAgICAgICAgICAgIC0gJ1x3c2NyaXB0LmV4ZScKICAgICAgICAgICAgLSAnXGNzY3JpcHQuZXhlJwogICAgICAgICAgICAtICdcaGguZXhlJwogICAgICAgICAgICAtICdcbXNodGEuZXhlJwogICAgICAgICAgICAtICdcZm9yZmlsZXMuZXhlJwogICAgICAgICAgICAtICdccGluZy5leGUnCiAgICAgICAgLSBDb21tYW5kTGluZXxjb250YWluczoKICAgICAgICAgICAgIyAtICdzYyBzdG9wICcgIyBzdG9wcyBhIHN5c3RlbSBzZXJ2aWNlICMgY2F1c2VzIEZQcwogICAgICAgICAgICAtICcgLU5vUCAnICAjIE9mdGVuIHVzZWQgaW4gbWFsaWNpb3VzIFBvd2VyU2hlbGwgY29tbWFuZHMKICAgICAgICAgICAgLSAnIC1XIEhpZGRlbiAnICAjIE9mdGVuIHVzZWQgaW4gbWFsaWNpb3VzIFBvd2VyU2hlbGwgY29tbWFuZHMKICAgICAgICAgICAgLSAnIC1kZWNvZGUgJyAgIyBVc2VkIHdpdGggY2VydHV0aWwKICAgICAgICAgICAgLSAnIC9kZWNvZGUgJyAgIyBVc2VkIHdpdGggY2VydHV0aWwKICAgICAgICAgICAgLSAnIC91cmxjYWNoZSAnICAjIFVzZWQgd2l0aCBjZXJ0dXRpbAogICAgICAgICAgICAtICcgLXVybGNhY2hlICcgICMgVXNlZCB3aXRoIGNlcnR1dGlsCiAgICAgICAgICAgIC0gJyAtZSogSkFCJyAgIyBQb3dlclNoZWxsIGVuY29kZWQgY29tbWFuZHMKICAgICAgICAgICAgLSAnIC1lKiBTVVZZSScgICMgUG93ZXJTaGVsbCBlbmNvZGVkIGNvbW1hbmRzCiAgICAgICAgICAgIC0gJyAtZSogU1FCRkFGZ0EnICAjIFBvd2VyU2hlbGwgZW5jb2RlZCBjb21tYW5kcwogICAgICAgICAgICAtICcgLWUqIGFXVjRJJyAgIyBQb3dlclNoZWxsIGVuY29kZWQgY29tbWFuZHMKICAgICAgICAgICAgLSAnIC1lKiBJQUInICAjIFBvd2VyU2hlbGwgbmNvZGVkIGNvbW1hbmRzCiAgICAgICAgICAgIC0gJyAtZSogUEFBJyAgIyBQb3dlclNoZWxsIGVuY29kZWQgY29tbWFuZHMKICAgICAgICAgICAgLSAnIC1lKiBhUUJsQUhnQScgICMgUG93ZXJTaGVsbCBlbmNvZGVkIGNvbW1hbmRzCiAgICAgICAgICAgIC0gJ3Zzc2FkbWluIGRlbGV0ZSBzaGFkb3dzJyAgIyBSYW5zb213YXJlCiAgICAgICAgICAgIC0gJ3JlZyBTQVZFIEhLTE0nICAjIHNhdmUgcmVnaXN0cnkgU0FNIC0gc3lza2V5IGV4dHJhY3Rpb24KICAgICAgICAgICAgLSAnIC1tYSAnICAjIFByb2NEdW1wCiAgICAgICAgICAgIC0gJ01pY3Jvc29mdFxXaW5kb3dzXEN1cnJlbnRWZXJzaW9uXFJ1bicgICMgUnVuIGtleSBpbiBjb21tYW5kIGxpbmUgLSBvZnRlbiBpbiBjb21iaW5hdGlvbiB3aXRoIFJFRyBBREQKICAgICAgICAgICAgLSAnLmRvd25sb2Fkc3RyaW5nKCcgICMgUG93ZXJTaGVsbCBkb3dubG9hZCBjb21tYW5kCiAgICAgICAgICAgIC0gJy5kb3dubG9hZGZpbGUoJyAgIyBQb3dlclNoZWxsIGRvd25sb2FkIGNvbW1hbmQKICAgICAgICAgICAgLSAnIC90aWNrZXQ6JyAgIyBSdWJldXMKICAgICAgICAgICAgLSAnZHBhcGk6OicgICAgICNNaW1pa2F0egogICAgICAgICAgICAtICdldmVudDo6Y2xlYXInICAgICAgICAjTWltaWthdHoKICAgICAgICAgICAgLSAnZXZlbnQ6OmRyb3AnICAgICAjTWltaWthdHoKICAgICAgICAgICAgLSAnaWQ6Om1vZGlmeScgICAgICAjTWltaWthdHoKICAgICAgICAgICAgLSAna2VyYmVyb3M6OicgICAgICAgI01pbWlrYXR6CiAgICAgICAgICAgIC0gJ2xzYWR1bXA6OicgICAgICAjTWltaWthdHoKICAgICAgICAgICAgLSAnbWlzYzo6JyAgICAgI01pbWlrYXR6CiAgICAgICAgICAgIC0gJ3ByaXZpbGVnZTo6JyAgICAgICAjTWltaWthdHoKICAgICAgICAgICAgLSAncnBjOjonICAgICAgI01pbWlrYXR6CiAgICAgICAgICAgIC0gJ3Nla3VybHNhOjonICAgICAgICNNaW1pa2F0egogICAgICAgICAgICAtICdzaWQ6OicgICAgICAgICNNaW1pa2F0egogICAgICAgICAgICAtICd0b2tlbjo6JyAgICAgICNNaW1pa2F0egogICAgICAgICAgICAtICd2YXVsdDo6Y3JlZCcgICAgICNNaW1pa2F0egogICAgICAgICAgICAtICd2YXVsdDo6bGlzdCcgICAgICNNaW1pa2F0egogICAgICAgICAgICAtICcgcDo6ZCAnICAjIE1pbWlrYXR6CiAgICAgICAgICAgIC0gJztpZXgoJyAgIyBQb3dlclNoZWxsIElFWAogICAgICAgICAgICAtICdNaW5pRHVtcCcgICMgUHJvY2VzcyBkdW1waW5nIG1ldGhvZCBhcGFydCBmcm9tIHByb2NkdW1wCiAgICAgICAgICAgIC0gJ25ldCB1c2VyICcKICAgIGNvbmRpdGlvbjogYWxsIG9mIHNlbGVjdGlvbioKZmFsc2Vwb3NpdGl2ZXM6CiAgICAtIEFkbWluaXN0cmF0aXZlIGFjdGl2aXR5CiAgICAtIFNjcmlwdHMgYW5kIGFkbWluaXN0cmF0aXZlIHRvb2xzIHVzZWQgaW4gdGhlIG1vbml0b3JlZCBlbnZpcm9ubWVudAogICAgLSBNb25pdG9yaW5nIGFjdGl2aXR5CmxldmVsOiBoaWdo&pipelineYml=)

Thanks :)
