### ISSUE TITLE
Azure backed?

### ISSUE THREAD

**Issue by jeremyhagan** [magicsword-io/sigconverter.io#38]
Hi and thanks for your work.

Where does the Azure backend come from? This doesn't appear as an available backend using sigma-cli and I would love to use it in my own environment for Sentinel

Cheers,
Jeremy.

**Comment by M3NIX** [comment]
At the moment the backend which is shown as `azure` at [sigconverter.com](https://sigconverter.io/) is the following:
https://github.com/sifex/pySigma-backend-azure

As this is no longer maintained you should instead use the microsoft365defender backend (https://github.com/AttackIQ/pySigma-backend-microsoft365defender)

We will soon remove the azure backend dependency in our repository
