### ISSUE TITLE
Add RSA NetWitness to sigma rule converter [sigconverter.io]

### ISSUE THREAD

**Issue by RaffeeJoffer** [magicsword-io/sigconverter.io#42]
Can you please add RSA NetWitness to the sigma rule converter ?
If it's not possible can you give me a way to convert sigma rule to RSA NetWitness rule format ?
Thanks

**Comment by nasbench** [comment]
The backend used and supported by sigconverter are listed in here https://github.com/SigmaHQ/pySigma-plugin-directory/blob/main/pySigma-plugins-v1.json

PySigma backends are contributed by the community and unfortunately there isn't a RSA NetWitness one created.

You could try joining the [discord](https://discord.gg/kQQBn5W2z5) server. And ask for it in the #help section. Maybe someone is willing to help you dev one.
