### ISSUE TITLE
Beta support for Panther backend (and others)

### ISSUE THREAD

**Issue by joshnck** [magicsword-io/sigconverter.io#48]
My last PR removed support for a handful of backends that have since been updated. One being https://github.com/panther-labs/pySigma-backend-panther/issues/57#issuecomment-2356070535.

I'm dropping this here as a reminder for myself to re-enable those backends and test them in the beta converter.

**Comment by M3NIX** [comment]
With our latest update where we had some bigger changes, this backend was added. You can test it here:
https://sigconverter.io/#version=1.0.4&backend=panther&format=python&pipeline=crowdstrike_fdr
