### ISSUE TITLE
Migrating to pySigma-backend-crowdstrike

### ISSUE THREAD

**Issue by moullos** [magicsword-io/sigconverter.io#49]
The [pySigma-pipeline-crowdstrike](https://pypi.org/project/pysigma-pipeline-crowdstrike/) package, has been replaced with[ pySigma-backend-crowdstrike](https://pypi.org/project/pysigma-backend-crowdstrike/). This new package adds support for CrowdStrike Logscale sigma translations.

**Comment by M3NIX** [comment]
With our latest update where we had some bigger changes this backend was added. You can test it here:
https://sigconverter.io/#version=1.0.4&backend=log_scale&format=default&pipeline=crowdstrike_fdr
