### ISSUE TITLE
Translation to Microsoft Defender?

### ISSUE THREAD

**Issue by osnolanarf** [magicsword-io/sigconverter.io#56]
Hi
I don't know since when but right now the Microsoft Defender (or KQL) option does not appear in the “target” field.
Is it a bug or this language is no longer supported?
Thank you.

**Comment by M3NIX** [comment]
Hi, with our latest code refactoring we had some problems while having KQL backend installed alongside the other backends. As we have finished the refactor, I will try to troubleshoot the problem and re-enable it as soon as possible. Sorry for the inconvenience of removing it.

**Comment by osnolanarf** [comment]
Hi.
Sorry, I just saw the status of this issue. Completed, what does it mean? Because except my mistake, “Defender”(Kusto) is not available yet. 
Thanks, best regards.

**Comment by M3NIX** [comment]
Hi @osnolanarf, the code was adjusted and we just recently noticed that we seem to have a problem with the deployment. We are investigating it atm. As soon as this is fixed the Kusto Backend will be finally available. I will ping you here again

**Comment by osnolanarf** [comment]
Its works! :)
